### ISSUE TITLE
Фичреквест: Открывать в новой вкладке

### ISSUE THREAD

**Issue by etomarat** [nicodimuscanis/brief-extension#3]
Привет! Очень хотелось бы чтобы результат открывался в новой вкладке, чтобы можно было что-то уточнить или углубиться в чтение. Сейчас даже назад вернуться нельзя, кнопка назад становится не активна в браузере после перехода на краткую версию

**Comment by nicodimuscanis** [comment]
Привет. Спасибо за обратную связь! 
Это функционал браузера (нельзя вернуться), не думаю, что с этим можно что-то сделать, но
1. В открывшейся вкладке есть кнопка внизу "перейти на оригинал" этого не достаточно?
2. В версии 0.4 есть также режим открыть в новом окне. Попробуйте его.
3. Можно вернуться назад, если выбрать режим открывать в текущей вкладке.

**Comment by etomarat** [comment]
Оу, не увидел опции. Сори. Режим "В новой вкладке" работает как надо, спасибо!
